// Generated by CoffeeScript 1.7.1
(function() {
  var express, router;
  var a = "Send DATA";


  express = require('express');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.render('step_all', {
      title: 'OAuth2.0Playground'
    });
  });

  module.exports = router;

}).call(this);
